# Generated by Django 3.2.18 on 2023-03-10 06:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack'), (4, 'Dessert'), (5, 'Drinks')])),
                ('main_ingedient', models.IntegerField(choices=[(0, 'Beef'), (1, 'Chicken'), (2, 'Fruits'), (3, 'Grains'), (4, 'Lamb'), (5, 'Seafood'), (6, 'Turkey'), (7, 'Vegetable')])),
                ('diet_type', recipeapp.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('Dairy-free', 'Dairy-free'), ('Egg free', 'Egg free'), ('Gluten-free', 'Gluten-free'), ('Nut free', 'Nut free'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('serves', models.PositiveIntegerField()),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Save as Draft'), (1, 'Publish Now!')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='recipe_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipeapp.recipe')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
