# Generated by Django 3.2.18 on 2023-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_ingedient',
            field=models.IntegerField(choices=[(0, 'Beef'), (1, 'Chicken'), (2, 'Fruits'), (3, 'Grains'), (4, 'Lamb'), (5, 'Pork'), (6, 'Seafood'), (7, 'Turkey'), (8, 'Vegetable')]),
        ),
    ]
