# Generated by Django 3.2.18 on 2023-03-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_recipe_main_ingedient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='main_ingedient',
            new_name='main_ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Moderate'), (2, 'Hard')], default=0),
            preserve_default=False,
        ),
    ]
