# Generated by Django 3.2.18 on 2023-03-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_recipe_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='meal',
        ),
    ]
