# Generated by Django 3.2.18 on 2023-04-01 05:00

from django.db import migrations, models
import recipeapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_remove_recipe_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(validators=[recipeapp.validators.textfield_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(validators=[recipeapp.validators.textfield_not_empty]),
        ),
    ]
