# Generated by Django 3.2.18 on 2023-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0008_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(verbose_name='Cooking Time (mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.IntegerField(choices=[(0, 'Beef'), (1, 'Chicken'), (2, 'Fruits'), (3, 'Grains'), (4, 'Lamb'), (5, 'Pork'), (6, 'Seafood'), (7, 'Turkey'), (8, 'Vegetable'), (9, 'Other')], verbose_name='Main Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack'), (4, 'Dessert'), (5, 'Drinks')], verbose_name='Meal Type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(verbose_name='Prep Time (mins)'),
        ),
    ]
