# Generated by Django 3.2.18 on 2023-04-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0009_auto_20230409_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(verbose_name='Cooking Time in Minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(verbose_name='Preparation Time in Minutes'),
        ),
    ]
