# Generated by Django 3.2.18 on 2023-04-15 19:16

from django.db import migrations, models
import recipeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_auto_20230409_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet_type',
            field=recipeapp.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('Dairy-free', 'Dairy-free'), ('Egg free', 'Egg free'), ('Gluten-free', 'Gluten-free'), ('Nut free', 'Nut free'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Diet Types (Optional)'),
        ),
    ]
