# Generated by Django 3.2.18 on 2023-04-17 08:30

from django.db import migrations, models
import recipeapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0011_alter_recipe_diet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(error_messages={'required': 'Please enter the description.'}, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(error_messages={'required': 'Please enter the ingredients.'}, validators=[recipeapp.validators.textfield_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(error_messages={'required': 'Please enter the cooking method.'}, validators=[recipeapp.validators.textfield_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(error_messages={'required': 'Please enter the title of the recipe.'}, max_length=100, unique=True),
        ),
    ]
